### ISSUE TITLE
Dependencies included as dev-master

### ISSUE THREAD

**Issue by skyellin** [kairosagency/GoogleAnalyticsServerSideBundle#1]
I notice that you include two dependencies (kairos/googleanalyticsserverside, and krizon/php-ga-measurement-protocol) as dev-master.  Isn't this going to cause problems for people using your bundle who have minimum stability set to stable?

**Comment by t0k4rt** [comment]
Hi, 
I wasn't sur people were using my bundle so hopefully you contacted me !
 I made a major update which is bc breaking so I had to tag different versions to clean things a little bit. 
If you want to keep the old bundle you have to change your composer and set version to ~1.0.0 where
You should take a look at version 2.0 which use google universal analytics and is far better than the library I previously used.
And actually I don't really know how to make sure people won't have problems with this update. 
Do you have any idea ?

**Comment by skyellin** [comment]
Well, one thing that (I think) would probably help people not to have problems would be to require tagged verions of your dependencies instead of dev-master, eg:

``` json
"kairos/googleanalyticsserverside": "1.0.*",
"krizon/php-ga-measurement-protocol": "0.1.*"
```

You'd have to tag the former bundle first.

I think this would solve a problem I've been having, at any rate.

**Comment by t0k4rt** [comment]
Hi, 
I updated and tagged the library needed in the bundle.
Also for you to know, there is now 2 version of the googleanalyticsserversidebundle :
- v1.0.x which should be the one you used 
- and the new v2.0.x that I advise you to use

I hope it will work for you now
